// src/ai/constants/intents.ts

import { IntentType } from "../types/intent.types";

export const INTENT_KEYWORDS: Record<IntentType, string[]> = {
  GREETING: [
    "hi",
    "hello",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "greetings",
  ],

  PRODUCT_SEARCH: [
    "show",
    "find",
    "search",
    "display",
    "list",
    "available",
    "have",
    "looking for",
    "need",
    "want",
    "recommend",
    "suggest",
    "options",
    "something",
    "activities",
    "under",
    "above",
    "between",
    "decorations",
  ],

  GENERAL_INFORMATION: [
    "who are you",
    "what is your name",
    "who created you",
    "tell me about",
    "what do you do",
    "what services",
    "what is this website",
    "tell me about the company",
    "about us",
    "company information",
    "how can you help",
  ],

  BOOKING: [
    "book",
    "booking",
    "book now",
    "reserve",
    "schedule",
    "confirm booking",
    "cancel booking",
    "track booking",
    "booking status",
    "order status",
  ],

  FAQ: [
    "contact",
    "phone",
    "mobile",
    "email",
    "address",
    "location",
    "office",
    "working hours",
    "timing",
    "open",
    "close",
    "price",
    "cost",
    "payment",
    "refund",
    "policy",
    "delivery",
    "services",
  ],

  SUPPORT: [
    "help",
    "support",
    "issue",
    "problem",
    "error",
    "complaint",
    "unable",
    "not working",
  ],

  RECOMMENDATION: [],
  CONTACT: [],
  THANK_YOU: [],
  GOODBYE: [],
  UNKNOWN: [],
};