// src/ai/constants/intents.ts

import { IntentType } from "../types/intent.types";

export const INTENT_KEYWORDS: Record<IntentType, string[]> = {
  GREETING: [
    "hi",
    "hello",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "greetings",
  ],

  PRODUCT_SEARCH: [
    "show",
    "find",
    "search",
    "display",
    "list",
    "available",
    "have",
    "looking for",
    "birthday",
    "anniversary",
    "baby shower",
    "welcome baby",
    "engagement",
    "wedding",
    "haldi",
    "mehendi",
    "proposal",
    "room decoration",
    "balloon decoration",
    "theme decoration",
    "decor",
    "decoration",
  ],

  RECOMMENDATION: [
    "recommend",
    "suggest",
    "best",
    "top",
    "popular",
    "premium",
    "luxury",
    "affordable",
    "budget",
    "cheap",
    "cheapest",
    "under",
    "above",
    "between",
    "most booked",
    "most popular",
    "which",
    "choose",
    "idea",
    "plan",
  ],

  BOOKING: [
    "book",
    "booking",
    "book now",
    "reserve",
    "schedule",
    "confirm booking",
    "cancel booking",
    "track booking",
    "booking status",
    "order status",
  ],

  FAQ: [
    "contact",
    "phone",
    "mobile",
    "email",
    "address",
    "location",
    "office",
    "working hours",
    "timing",
    "open",
    "close",
    "price",
    "cost",
    "payment",
    "refund",
    "policy",
    "delivery",
    "services",
  ],

  SUPPORT: [
    "help",
    "support",
    "issue",
    "problem",
    "error",
    "complaint",
    "unable",
    "not working",
  ],

  CONTACT: [
    "call",
    "contact",
    "phone",
    "mobile",
    "email",
    "whatsapp",
    "reach",
  ],

  THANK_YOU: [
    "thanks",
    "thank you",
    "thanks a lot",
    "thank you so much",
  ],

  GOODBYE: [
    "bye",
    "goodbye",
    "see you",
    "see you later",
    "take care",
  ],

  UNKNOWN: [],
};